album/urls.py
from django.urls import path
from . import views

app_name = 'album'

urlpatterns = [
    path('showall/', views.showall, name='showall'),
    path('upload/', views.upload, name='upload'),
]

foodmanager_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('foodmanager/', include('foodmanager.urls')),
    path('', include('accounts.urls')),
    path('album/', include('album.urls')),
]+  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

album/models.py
from django.db import models

# Create your models here.
class Image(models.Model):
    picture = models.ImageField(upload_to='images/')
    title = models.CharField(max_length=50)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '料理画像'
        verbose_name_plural = '料理画像'

album/forms.py
from django import forms
from .models import Image

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['picture', 'title']

album/views.py
from django.shortcuts import render
from .models import Image
from .forms import ImageForm

# Create your views here.

def showall(request):
    images = Image.objects.all()
    context = {'images':images}
    return render(request, 'album/showall.html', context)

def upload(request):
    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('album:showall')
    else:
        form = ImageForm()

    context = {'form':form}
    return render(request, 'album/upload.html', context)

templates/album/showall.html
<h1>Your Album</h1>

{% for image in images %}
    <img src='{{ MEDIA_URL }}{{image.picture}}' width=200>
    <h2>{{ image.title }}</h2>
{% endfor %}

<h2><a href="{% url 'album:upload' %}">Upload more</a></h2>

templates/album/upload.html
<h1>Please Upload</h1>

<form enctype="multipart/form-data" action="{% url 'album:upload' %}" method="post">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Upload">
</form>